# See Twilio.com for configuration information

TWILIO_ACCOUNT_SID = ENV['TWILIO_ACCOUNT_SID'] || "TWILIO ACCOUNT_SID NOT DEFINED"
TWILIO_AUTH_TOKEN = ENV['TWILIO_AUTH_TOKEN'] || "TWILIO AUTH_TOKEN NOT DEFINED"
TWILIO_CALLER_ID = ENV['TWILIO_CALLER_ID'] || "TWILIO CALLER_ID NOT DEFINED"
